### ISSUE TITLE
Improper Display of Distribution Group

### ISSUE THREAD

**Issue by paulchrisluke** [whynotearth/Volkswagen-email-corporate-communications-CMS#126] opened 2020-04-30 09:11 UTC
[ISSUE IN PROGRESS]

We are unable to see the names of the distribution group
![image](https://user-images.githubusercontent.com/5694308/80693543-5b385980-8afd-11ea-832b-aa004e8cf338.png)

**Comment by mort3za** [comment] 2020-04-30 09:37
duplicate of #127

**Closed by mort3za** 2020-04-30 09:37 UTC
Labels: duplicate
