### ISSUE TITLE
word wrap images instead of center on blue delta

### ISSUE THREAD

**Issue by bamboochow** [whynotearth/Volkswagen-email-corporate-communications-CMS#292] opened 2020-05-22 05:14 UTC
# Current 
Out text currently does not wrap around the images present, where below the image there is a cutoff in the text below 
![image](https://user-images.githubusercontent.com/5694308/81803473-eecc4a00-9541-11ea-9170-0d43f67952ab.png)

# Word Wrap 
This is an example of word wrap with image in our designs. Our images need to be wrapped instead of centered on our blue delta emails 
![image](https://user-images.githubusercontent.com/14948326/82633653-d76a1c80-9c25-11ea-9540-bd36598d0776.png)

**Comment by mort3za** [comment] 2020-05-25 07:09
duplicate of https://github.com/whynotearth/Volkswagen-email-corperate-communications/issues/102

**Closed by mort3za** 2020-05-25 07:09 UTC
Labels: duplicate
